name: haas700                                       # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: rel_3.3.0                                    # <必选项> 组件版本号
description: HaaS 700 board.                        # <必选项> 建议至少20字以上
type: board                                         # <必选项> 组件类型，为：solution, chip, board, common
tag: 核心模块                                       # <可选项> 组件分类，缺省值： ''
