name: lora_p2p_demo
version: rel_3.3.0
description: demostrate the p2p-comunication over lora radio
type: solution

solution:
  cpu_id: cpu0
  board_name: haas100

depends:
  - cli: rel_3.3.0
  - haas100: rel_3.3.0

source_file:
  - "*.c"
