name: lora_p2p_demo
version: master
description: demostrate the p2p-comunication over lora radio
type: solution

solution:
  cpu_id: cpu0
  board_name: haas100

depends:
  - cli: master
  - haas100: master

source_file:
  - "*.c"
