name: miniapp_agent_demo
version: dev_aos                                     # <必选项> 组件版本号
description: AliOS Things LinkSDK Data Model Demo

type: solution

solution:
  cpu_id: cpu0
  board_name: haas100
  # board_name: board_dummy
  # toolchain_prefix: csky-abiv2-elf
  # cpu_name: CK805EF
  # vendor_name: thead
  # chip_name: 'csi_ch2201'
  # ld_script: configs/gcc_eflash.ld
  # ld_script: gcc_eflash.ld

depends:                                       # 该组件依赖其他的组件
  - linksdk: dev_aos
  - haas100: dev_aos
  - mbedtls: dev_aos
  - netmgr: dev_aos
  - ble_netconfig: dev_aos
  - cli: dev_aos
  - kv: dev_aos
  - debug: dev_aos
  - lwip: dev_aos
  - uservice: dev_aos
  - wifi: dev_aos

## 第五部分：配置信息
#def_config:                              # 组件的可配置项

# 源文件
source_file:
  - "maintask.c"
  - "config_kv_demo.c"
  - "ble_net_config_demo.c"
  - "data_model_basic_demo.c"
