name: miniapp_agent_demo
version: master                                     # <必选项> 组件版本号
description: AliOS Things LinkSDK Data Model Demo

type: solution

solution:
  cpu_id: cpu0
  board_name: haas100
  # board_name: board_dummy
  # toolchain_prefix: csky-abiv2-elf
  # cpu_name: CK805EF
  # vendor_name: thead
  # chip_name: 'csi_ch2201'
  # ld_script: configs/gcc_eflash.ld
  # ld_script: gcc_eflash.ld

depends:                                       # 该组件依赖其他的组件
  - linksdk: master
  - mbedtls: master
  - netmgr: master
  - ble_netconfig: master
  - cli: master
  - kv: master
  - debug: master
  - lwip: master
  - uservice: master
  - wifi: master

# supported_boards 中记录当前组件能支持的所有板子
supported_boards:
  - haas100: master
  - haas200: master
  - haaseduk1: master

## 第五部分：配置信息
def_config:                              # 组件的可配置项
  CONFIG_BT_RX_STACK_SIZE: 4096

  # 源文件
source_file:
  - "maintask.c"
