name: auto_demo
version: rel_3.3.0                                     # <必选项> 组件版本号
description: 在物联网平台创建电动小车，可以通过钉钉小程序进行控制电动小车的运动

type: solution

solution:
  cpu_id: cpu0
  board_name: haas100
  # board_name: board_dummy
  # toolchain_prefix: csky-abiv2-elf
  # cpu_name: CK805EF
  # vendor_name: thead
  # chip_name: 'csi_ch2201'
  # ld_script: configs/gcc_eflash.ld
  # ld_script: gcc_eflash.ld

depends:                                       # 该组件依赖其他的组件
  - linksdk: rel_3.3.0
  - haas100: rel_3.3.0
  - mbedtls: rel_3.3.0
  - netmgr: rel_3.3.0
  - base: rel_3.3.0
  - adc: rel_3.3.0
  - i2c: rel_3.3.0
  - spi: rel_3.3.0
  - uart: rel_3.3.0
  - flash: rel_3.3.0
  - pwm: rel_3.3.0
  - watchdog: rel_3.3.0
  - gpio: rel_3.3.0
  - qspi: rel_3.3.0
  - timer: rel_3.3.0
  - wifi: rel_3.3.0
  - lwip: rel_3.3.0
  - uservice: rel_3.3.0
  - cli: rel_3.3.0
## 第五部分：配置信息
#def_config:                              # 组件的可配置项

# 源文件
source_file:
  - "maintask.c"
  - "main.c"
  - "data_model_basic_demo.c"
  - "auto_app.c"
