
## 第一部分： 基础信息
name: uvoice                                         # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: dev_aos                                     # <必选项> 组件版本号
description: uvoice是一个语音功能组件，包括播放器/播放控制、录音、编解码、在线播放、流媒体播放、TTS等功能 .   # <必选项> 建议至少20字以上
type: common                                        # <必选项> 组件类型，为：solution, chip, board, common, sdk

tag: 核心模块                                       # <可选项> 组件分类，缺省值： ''
keywords:                                           # <可选项> 标签，会影响到组件被搜索的效果，合理的标签很重要
  - uvoice
license: Apache license v2.0                        # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
   - ulog: dev_aos
   - osal_aos: dev_aos
   - a2sa: dev_aos
   - mbedtls: dev_aos

## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
    #cflag: -g -O0
  define:
    - __os_alios_things__
    - UVOICE_RELEASE_VERSION_MAIN=1
    - UVOICE_RELEASE_VERSION_SUB=0
    - UVOICE_EVENT_BY_BUFFER_QUEUE=1
    - AUDIO_CACHE_ENABLE=1 
    - UVOICE_EVENT_ENABLE=1
    
  internal_include:
    - internal
    - stream
    - audio
    - codec/opensource/pvmp3/include ? <DECODER_PV_MP3_ENABLE>
    - codec/opensource/pvaac/include ? <DECODER_PV_M4A_ENABLE>
    - codec/opensource/pvaac/oscl ? <DECODER_PV_M4A_ENABLE>
    - application/alicloudtts/include ? <ALICLOUD_TTS_SUPPORT>
  include:
    - include
    - internal
    - application/alicloudtts/include

# source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
#   - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件
source_file:
    - uvoice.c
    - common/event.c
    - common/ringbuffer.c
    - common/urlencode.c
    - media/uvoice_format.c
    - media/uvoice_codec.c
    - media/uvoice_stream.c
    - media/uvoice_wave.c
    - audio/audio_stream.c
    - audio/audio_common.c
    - audio/audio_mixer.c
    - audio/audio_process.c
    - audio/audio_trigger.c
    - media/uvoice_fade.c ? <UVOICE_PLAYER_ENABLE>
    - media/uvoice_player.c ? <UVOICE_PLAYER_ENABLE>
    - test/test_player.c ? <UVOICE_PLAYER_ENABLE>
    - media/uvoice_recorder.c ? <UVOICE_RECORDER_ENABLE>
    - test/test_recorder.c ? <UVOICE_RECORDER_ENABLE>
    - media/uvoice_mlist.c ? <UVOICE_MLIST_ENABLE>
    - stream/uvoice_file.c ? <UVOICE_FILE_ENABLE>
    - stream/uvoice_http.c ? <UVOICE_HTTP_ENABLE>
    - stream/uvoice_cache.c ? <UVOICE_HTTP_ENABLE>
    - stream/uvoice_ssl.c ? <UVOICE_HTTPS_ENABLE>
    - stream/uvoice_download.c ? <UVOICE_DOWNLOAD_ENABLE>
    - connect/uvoice_ws.c ? <UVOICE_WS_ENABLE>
    - stream/uvoice_hls.c ? <UVOICE_HLS_ENABLE>
    - stream/uvoice_partition.c ? <UVOICE_PARTITION_ENABLE>
    - codec/pvmp3_decoder.c ? <DECODER_PV_MP3_ENABLE>
    - codec/opensource/pvmp3/src/*.c ? <DECODER_PV_MP3_ENABLE>
    - codec/pvaac_decoder.c ? <DECODER_PV_M4A_ENABLE>
    - codec/opensource/pvaac/src/*.cpp ? <DECODER_PV_M4A_ENABLE>
    - codec/opensource/pvaac/src/*.c ? <DECODER_PV_M4A_ENABLE>
    - application/alicloudtts/*.c ? <ALICLOUD_TTS_SUPPORT>
    - test/test_tts.c ? <ALICLOUD_TTS_SUPPORT>
    - audio/hal/haas100/uvoice_pcm.c
    - example/uvoice_example.c


## 第五部分：配置信息
def_config:                              # 组件的可配置项
   UVOICE_BUILD_RELEASE: 1
   UVOICE_PLAYER_ENABLE: 1
   UVOICE_RECORDER_ENABLE: 1
   UVOICE_MLIST_ENABLE: 0
   UVOICE_FILE_ENABLE: 1
   UVOICE_HTTP_ENABLE: 1
   UVOICE_HTTPS_ENABLE: 1 
   UVOICE_DOWNLOAD_ENABLE: 1    
   UVOICE_HLS_ENABLE: 1   
   DECODER_PV_MP3_ENABLE: 1
   DECODER_PV_M4A_ENABLE: 1 
   ALICLOUD_TTS_SUPPORT: 1
   UVOICE_TTS_ENABLE: 1


## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相当路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径
install:
  - dest: "include"
    source:
      - "include/*.h"
