name: linksdk_demo
version: master                                     # <必选项> 组件版本号
description: 基于LinkSDK实现设备连接阿里云，用户可以通过阿里云物联网平台查看设备的在线状态、上下行数据等。

type: solution

solution:
  cpu_id: cpu0
  # board_name: haas100
  # board_name: board_dummy
  # toolchain_prefix: csky-abiv2-elf
  # cpu_name: CK805EF
  # vendor_name: thead
  # chip_name: 'csi_ch2201'
  # ld_script: configs/gcc_eflash.ld
  # ld_script: gcc_eflash.ld

# 编译前，需要将当前需要编译的板子添加到depends中，同时修改board_name
depends:                                       # 该组件依赖其他的组件
  - linksdk: master
  # - haas100: master
  - mbedtls: master
  - netmgr: master
  - lwip: master
  - uservice: master
  - wifi: master
  - cli: master

# supported_boards 中记录当前组件能支持的所有板子
supported_boards:
  - haas100: master
  - haas200: master
  - haaseduk1: master

## 第五部分：配置信息
#def_config:                              # 组件的可配置项
def_config:
    CLI_IOBOX_ENABLE: 1        # 使能文件系统

# 源文件
source_file:
  - "maintask.c"
  - "main.c"
  - "data_model_basic_demo.c"
