
## 第一部分： 基础信息
name: little_ui
version: rel_3.3.0
description: "component built by cmake"             # <必选项> 建议至少20字以上
type: common                                        # <必选项> 组件类型，为：solution, chip, board, common, sdk

tag:                                                # <可选项> 组件分类，缺省值： ''
license: Apache license v2.0                        # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
depends:
  - espressif_esp32: rel_3.3.0
  - osal_aos: rel_3.3.0
## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  include:
    - ./
    - driver/
    - 3rdparty/
    - 3rdparty/lvgl/
    - 3rdparty/lvgl/src/
    - 3rdparty/lvgl/src/hal/
    - driver/i2c_manager/
    - driver/i2c_manager/i2c_manager/
    - driver/axp192/
    - driver/lvgl_esp32_drivers/
  #prebuild_script: build_cmake.sh

source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
  # lv_bindings
  - 3rdparty/lvgl/src/core/*.c
  - 3rdparty/lvgl/src/draw/*.c
  - 3rdparty/lvgl/src/extra/*.c
  - 3rdparty/lvgl/src/extra/others/snapshot/*.c
  - 3rdparty/lvgl/src/extra/layouts/flex/*.c
  - 3rdparty/lvgl/src/extra/themes/basic/*.c
  - 3rdparty/lvgl/src/extra/widgets/animimg/*.c
  - 3rdparty/lvgl/src/extra/widgets/calendar/*.c
  - 3rdparty/lvgl/src/extra/layouts/grid/*.c
  - 3rdparty/lvgl/src/extra/themes/mono/*.c
  - 3rdparty/lvgl/src/extra/widgets/imgbtn/*.c
  - 3rdparty/lvgl/src/extra/widgets/keyboard/*.c
  - 3rdparty/lvgl/src/extra/widgets/led/*.c
  - 3rdparty/lvgl/src/extra/widgets/msgbox/*.c
  - 3rdparty/lvgl/src/extra/widgets/list/*.c
  - 3rdparty/lvgl/src/extra/widgets/colorwheel/*.c
  - 3rdparty/lvgl/src/font/*.c
  - 3rdparty/lvgl/src/extra/widgets/tabview/*.c
  - 3rdparty/lvgl/src/extra/widgets/spinbox/*.c
  - 3rdparty/lvgl/src/extra/widgets/spinner/*.c
  - 3rdparty/lvgl/src/extra/themes/default/*.c
  - 3rdparty/lvgl/src/extra/widgets/tileview/*.c
  - 3rdparty/lvgl/src/extra/widgets/win/*.c
  - 3rdparty/lvgl/src/extra/widgets/meter/*.c
  - 3rdparty/lvgl/src/extra/widgets/span/*.c
  - 3rdparty/lvgl/src/extra/widgets/chart/*.c
  - 3rdparty/lvgl/src/gpu/*.c
  - 3rdparty/lvgl/src/hal/*.c
  - 3rdparty/lvgl/src/misc/*.c
  - 3rdparty/lvgl/src/widgets/*.c
  - 3rdparty/lvgl/src/extra/libs/fsdrv/*.c
  - 3rdparty/lvgl/src/extra/libs/sjpg/*.c
  - 3rdparty/lvgl/src/extra/libs/png/*.c

  - driver/axp192/axp192.c

  - driver/i2c_manager/i2c_manager/i2c_manager.c

  # - example/example.c
  - driver/lvgl_esp32_drivers/lvgl_tft/esp_lcd_backlight.c
  - driver/lvgl_esp32_drivers/lvgl_i2c/i2c_manager.c
  - driver/lvgl_esp32_drivers/lvgl_tft/disp_driver.c
  - driver/lvgl_esp32_drivers/lvgl_helpers.c
  - driver/lvgl_esp32_drivers/lvgl_touch/touch_driver.c
  - driver/lvgl_esp32_drivers/lvgl_touch/ft6x36.c
  - driver/lvgl_esp32_drivers/lvgl_tft/ili9341.c
  - driver/lvgl_esp32_drivers/lvgl_tft/disp_spi.c

## 第五部分：配置信息
# def_config:                              # 组件的可配置项
#   CONFIG_DEBUG: y
#   CONFIG_PARAM_NOT_CHECK: y
#   CONFIG_CLI: y
def_config:
  # LVGL info
  #LV_MICROPYTHON: 1
# # 第六部分：安装信息
#  install:
#    - dest: include/                       # 安装的目的路径 dest是相当路径，通常是相对于YoC SDK 安装目录
#      source:                              # 安装源列表
#       - src/*.h                           # 支持通配符，相对路径
  
# # 第七部分：导出部分
#  export:
#    - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相当路径
#      source:                                # 安装源列表
#        - "bootimgs/boot"
#        - "bootimgs/tee"
#        - "bootimgs/mtb"
#        - "configs/config.yaml"
  
  
