name: chip_vexpress_a9
version: dev_aos
description: drivers & sdk for mcu vexpress-a9
type: chip
tag: ""
keywords:
  - base
license: Apache license v2.0

depends:
  - libc_stub: dev_aos 
  - armv7a: dev_aos
  - rhino: dev_aos
  - osal_aos: dev_aos
  - uservice: dev_aos
  - init: dev_aos
  - lwip: dev_aos
  - cli: dev_aos
  - flash: dev_aos
  - uart: dev_aos
  - gpio: dev_aos
  - watchdog: dev_aos
  - timer: dev_aos
  - wifi: dev_aos

build_config:
  cflag: >
    -mcpu=cortex-a9
    -mfpu=vfpv3
    -mfloat-abi=hard
    -fno-delete-null-pointer-checks
    -mno-unaligned-access
    -Wall
    -Wno-format

build_config:
  cflag: >
    -mcpu=cortex-a9
    -mfpu=vfpv3
    -mfloat-abi=hard
    -fno-delete-null-pointer-checks
    -mno-unaligned-access
    -Wall
    -Wno-format

build_config:
  cflag: >
    -mcpu=cortex-a9
    -mfpu=vfpv3
    -mfloat-abi=hard
    -fno-delete-null-pointer-checks
    -mno-unaligned-access
    -Wall
    -Wno-format

build_config:
  cflag: >
    -mcpu=cortex-a9
    -mfpu=vfpv3
    -mfloat-abi=hard
    -fno-delete-null-pointer-checks
    -mno-unaligned-access
    -Wall
    -Wno-format

build_config:
  cflag: >
    -mcpu=cortex-a9
    -mfpu=vfpv3
    -mfloat-abi=hard
    -fno-delete-null-pointer-checks
    -mno-unaligned-access
    -Wall
    -Wno-format
    -Wno-unused-variable
    -Wno-unused-parameter
    -Wno-implicit-function-declaration
    -Wno-type-limits
    -Wno-sign-compare
    -Wno-pointer-sign
    -Wno-uninitialized
    -Wno-return-type
    -Wno-unused-function
    -Wno-unused-but-set-variable
    -Wno-unused-value
    -Wno-strict-aliasing
    -Wno-incompatible-pointer-types
    -fno-builtin-memcopy
    -fno-builtin-memmove
    -fno-builtin-memset
  cxxflag: >
    -std=c++11
    -D_GLIBCXX_HAS_GTHREADS
    -mcpu=cortex-a9
    -mfpu=vfpv3
    -mfloat-abi=hard
    -mno-unaligned-access
  asmflag: >
    -mcpu=cortex-a9
    -mfpu=vfpv3
    -mfloat-abi=hard
  ldflag: >
    -mcpu=cortex-a9
    -mfpu=vfpv3
    -mfloat-abi=hard
    -Wl,--gc-sections
    -Wl,-no-whole-archive
  include:
    - drivers/
    - drivers/arch/
    - drivers/smp/
    - drivers/include/
  internal_include:
    - drivers/audio/
    - drivers/uart/inc/
    - hal/os_api/freertos_aos/
    - hal/os_api/inc/
    - hal/os_api/include/
    - hal/timer/inc/
    - drivers/gpio/inc/
    - drivers/i2c/inc/
    - drivers/eint/inc/
    - drivers/clk/inc/
    - drivers/spmc/inc/
    - drivers/auxadc/inc/
    - drivers/trng/inc/
    - drivers/lib/gcpu/inc/
    - drivers/connectivity/wlan/
    - drivers/clcd/
    - drivers/keypad/inc/
    - drivers/pwm/inc/
    - drivers/irq/gic/gicv2/

source_file:
  - "aos/aos.c"
  - "aos/soc_impl.c"
  - "aos/hook_impl.c"
  - "hal/uart.c"
  - "hal/hw.c"
  - "hal/gpio.c"
  # - "hal/adc.c"
  - "hal/flash.c"
  # - "hal/wdg.c"
  # - "hal/wifi_port.c ? <AOS_COMP_LWIP>"
  - "hal/os_api/freertos_aos/freertos_to_aos.c"
  - "hal/os_api/src/os_event.c"
  - "hal/os_api/src/os_mem.c"
  - "hal/os_api/src/os_mutex.c"
  - "hal/os_api/src/os_queue.c"
  - "hal/os_api/src/os_sem.c"
  - "hal/os_api/src/os_task.c"
  - "hal/os_api/src/os_timer.c"
  - "hal/timer/arch_timer_v1.c"
  # - "drivers/gpio/src/mt_gpio.c"
  # - "drivers/eint/src/eint.c"
  # - "drivers/clk/src/mtk_clk.c"
  # - "drivers/clk/src/clk_mt8512.c"
  # - "drivers/clk/src/mtk_pd.c"
  # - "drivers/clk/src/mtk_pd_mt8512.c"
  # - "drivers/clk/src/mtk_clkdbg.c"
  # - "drivers/clk/src/mtk_clkdbg_mt8512.c"
  # - "drivers/spmc/src/mtspmc.c"
  # - "drivers/trng/src/mt_rng.c"
  # - "drivers/auxadc/src/mt_auxadc.c"
  - "drivers/connectivity/wlan/ethernetif.c"
  - "drivers/connectivity/wlan/drv_smc911x.c"
  # - "drivers/clcd/drv_clcd.c ? <AOS_COMP_FBDEV>"
  # - "drivers/input/drv_mouse.c ? <AOS_COMP_INPUTCORE>"
  # - "drivers/pwm/src/mt_pwm.c"
  # - "drivers/audio/audio_vexpress_a9.c"
  # - "drivers/audio/drv_ac97.c"
  # - "drivers/audio/drv_pl041.c"
  # - "drivers/ptimer.c"
  - "drivers/uart_pl011.c"
  - "drivers/drv_timer.c"
  # - "drivers/drv_norflash.c"
  - "drivers/smp/secondary.c"
  - "drivers/smp/smp_int.c"
  - "drivers/smp/smp_load.c"
  - "drivers/smp/smp_sync.c"
  - "drivers/vendor_stub.c"
  - "aos/gicv2_api_adapter.c"
  - "drivers/irq/irqdesc.c"
  - "drivers/irq/gic/gic_common.c"
  - "drivers/irq/gic/gicv2/irqchip_gicv2.c"
  # - "drivers/gic.c"
  # - "drivers/irq.c"
  # - "hal/gic.c"
  # - "hal/arm_gic_v3/mt_gic_v3.c"

def_config:
  STDIO_UART: 0
  USE_MX1290: 1
  CLI_CONFIG_STACK_SIZE: 4096
  CONFIG_LWIP_VERSION: "lwip2.0.0"
  CONFIG_LWIP_V200: 1
  # CONFIG_NO_LWIP: 1
  RHINO_CONFIG_SYS_STATS: 1
  RHINO_CONFIG_SPINLOCK_DEBUG: 1

chip:
  arch_name: arm
  cpu_name: cortex-a9
  vendor_name: ARM
  toolchain_prefix: arm-none-eabi
  ld_script: flash.ld
