name: posix
version: rel_3.3.0
description: 支持POSIX标准API
type: common

tag: 核心模块
keywords:
  - base
license: Apache license v2.0

depends:
  - osal_aos: rel_3.3.0
  - select: rel_3.3.0

build_config:
  include:
    - include

source_file:
  - "src/*.c"

install:
  - dest: "include"
    source:
      - "include/*.h"
