name: posix
version: master
description: 支持POSIX标准API
type: common

tag: 核心模块
keywords:
  - base
license: Apache license v2.0

depends:
  - osal_aos: master
  - select: master ? <!ESP_PLATFORM>

build_config:
  include:
    - include ? <!ESP_PLATFORM>
    - esp_idf/include ? <ESP_PLATFORM>
source_file:
  - src/*.c ? <!ESP_PLATFORM>
  - esp_idf/*c ? <ESP_PLATFORM>
  - export.c ? <CONFIG_DM>
install:
  - dest: "include"
    source:
      - "include/*.h"
