name: linksdk_gateway_demo
version: rel_3.3.0                                     # <必选项> 组件版本号
description: 基于LinkSDK实现设备作为网关搭建子设备与远端交互的通道。

type: solution

solution:
  cpu_id: cpu0
  board_name: haas100
  # board_name: board_dummy
  # toolchain_prefix: csky-abiv2-elf
  # cpu_name: CK805EF
  # vendor_name: thead
  # chip_name: 'csi_ch2201'
  # ld_script: configs/gcc_eflash.ld
  # ld_script: gcc_eflash.ld

depends:                                       # 该组件依赖其他的组件
  - linksdk: rel_3.3.0
  - mbedtls: rel_3.3.0
  - netmgr: rel_3.3.0
  - lwip: rel_3.3.0
  - uservice: rel_3.3.0
  - wifi: rel_3.3.0
  - cli: rel_3.3.0

# supported_boards 中记录当前组件能支持的所有板子
supported_boards:
  - haas100: rel_3.3.0
  - haas200: rel_3.3.0
  - haaseduk1: rel_3.3.0
## 第五部分：配置信息
def_config:                              # 组件的可配置项
  #以下配置同时仅允许打开其中一项

# 源文件
source_file:
  - "main.c"
  - "maintask.c"
  - "subdev_basic_demo.c"
