## 第一部分： 基础信息
name: amp                                     # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: rel_3.3.0                                     # <必选项> 组件版本号
description: AliOS Things mini program                             # <必选项> 建议至少20字以上
type: common                                        # <必选项> 组件类型，为：solution, chip, board, common, sdk

tag: 应用框架                                        # <可选项> 组件分类，缺省值： ''
keywords:                                           # <可选项> 标签，会影响到组件被搜索的效果，合理的标签很重要
  - amp
  - JavaScript
  - IoT Platform
homepage: https://help.aliyun.com/document_detail/174810.html
license: Apache-2.0 License                        # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
depends:
  - osal_aos: rel_3.3.0
  - ulog: rel_3.3.0
  - uagent: rel_3.3.0
  - kv: rel_3.3.0
  - mbedtls: rel_3.3.0
  - cjson: rel_3.3.0
  - uvoice: rel_3.3.0
  - linksdk: rel_3.3.0
  - ota: rel_3.3.0
  - netmgr: rel_3.3.0
  - littlefs: rel_3.3.0
  - http: rel_3.3.0
  - amp_adapter: rel_3.3.0
  - ble_host: rel_3.3.0
  - uagent: rel_3.3.0
  - littlevgl: rel_3.3.0
  - ble_netconfig: rel_3.3.0

## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  define:
    - CONFIG_USING_TLS=1
    - __AOS_AMP__=1
  internal_include:
    - engine/duktape_engine ? <CONFIG_ENGINE_DUKTAPE>
    - engine/duktape_engine/addons ? <CONFIG_ENGINE_DUKTAPE>
    - engine/duktape_engine/addons/advanced/aiot ? <CONFIG_ENGINE_DUKTAPE>
    - engine/duktape_engine/duktape ? <CONFIG_ENGINE_DUKTAPE>
    - engine/duktape_engine/startup ? <CONFIG_ENGINE_DUKTAPE>
    - engine/quickjs_engine/quickjs ? <CONFIG_ENGINE_QUICKJS>
    - engine/quickjs_engine/addons/common ? <CONFIG_ENGINE_QUICKJS>
    - engine/quickjs_engine/aos_port ? <CONFIG_ENGINE_QUICKJS>
    - engine/quickjs_engine/addons ? <CONFIG_ENGINE_QUICKJS>
    - engine/quickjs_engine/addons/utils/crypto ? <CONFIG_ENGINE_QUICKJS>
    - engine/quickjs_engine ? <CONFIG_ENGINE_QUICKJS>
    - main
    - services/amp_utils
    - utils/list
    - services/app_mgr
    - services/board_mgr
    - services/recovery
    - services/amp_boot
    - utils/checksum

# source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
#   - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件
source_file:
  - engine/duktape_engine/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/advanced/audio/module_audioplayer.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/advanced/audio/module_tts.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/advanced/aiot/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/advanced/blecfgnet/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/advanced/ota/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/hardware/adc/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/hardware/can/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/hardware/dac/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/hardware/gpio/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/hardware/i2c/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/hardware/ir/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/hardware/lcd/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/hardware/pwm/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/hardware/onewire/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/hardware/rtc/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/hardware/spi/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/hardware/timer/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/hardware/uart/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/hardware/wdg/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/network/cellular/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/network/http/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/network/iot/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/network/mqtt/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/network/tcp/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/network/udp/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/network/wifi/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/network/netmgr/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/wireless/bt_host/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/utils/builtin/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/utils/crypto/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/utils/fs/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/utils/kv/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/utils/pm/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/utils/system/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/utils/systimer/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/utils/log/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/addons/utils/checksum/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/duktape/*.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/duktape_engine/startup/app_entry.c ? <CONFIG_ENGINE_DUKTAPE>
  - engine/quickjs_engine/quickjs/quickjs.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/quickjs/libregexp.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/quickjs/libunicode.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/quickjs/cutils.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/quickjs/libbf.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/aos_port/aos_jquick_mutex.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/startup/quickjs_init.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/startup/quickjs_module_load.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/repl.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/libc/quickjs_libc.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/hardware/gpio/module_gpio.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/wireless/bt_host/module_bt_host.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/wireless/bt_host/bt_host_adapter.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/wireless/bt_host/bt_gatts_adapter.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/utils/crypto/module_crypto.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/utils/crypto/crypto_adapter.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/utils/crypto/cbc_mode.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/utils/checksum/module_checksum.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/hardware/wdg/module_wdg.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/hardware/spi/module_spi.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/hardware/rtc/module_rtc.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/hardware/pwm/module_pwm.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/hardware/uart/module_uart.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/hardware/onewire/module_onewire.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/hardware/adc/module_adc.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/hardware/dac/module_dac.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/hardware/i2c/module_i2c.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/hardware/lcd/module_lcd.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/hardware/timer/module_timer.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/network/http/module_http.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/network/netmgr/module_netmgr.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/advanced/aiot/*.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/advanced/ota/*.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/utils/systimer/module_systimer.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/utils/system/module_system.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/utils/log/module_log.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/utils/fs/module_fs.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/utils/kv/module_kv.c ? <CONFIG_ENGINE_QUICKJS>
  - engine/quickjs_engine/addons/repl/module_repl.c ? <CONFIG_ENGINE_QUICKJS>
  - jslib/bytecode/*.c ? <CONFIG_ENGINE_QUICKJS>
  - main/*.c
  - services/amp_utils/*.c
  - services/app_mgr/*.c
  - services/board_mgr/*.c
  - services/recovery/*.c
  - services/amp_boot/*.c
  - example/amp_example.c
  - utils/checksum/*.c

## 第五部分：配置信息
def_config:                              # 组件的可配置项
    #CONFIG_ENGINE_DUKTAPE: 1
    CONFIG_ENGINE_QUICKJS: 1
    CONFIG_VERSION: '1.0'
    ULOG_CONFIG_ASYNC: 1                 #ulog需要默认支持异步模式
    ULOG_CONFIG_POP_FS: 1                #支持存储到文件系统
    #CONFIG_AMP_UI_SUPPORT : 1


## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相当路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径
install:
  - dest: "include"
    source:
      - "include/*.h"

## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相当路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"
