name: qrcode_demo                                   # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: master                                    # <必选项> 组件版本号
description: QR code demo example.                  # <必选项> 建议至少20字以上
type: solution                                      # <必选项> 组件类型，为：solution, chip, board, common
tag: 核心模块                                       # <可选项> 组件分类，缺省值： ''

solution:
  cpu_id: cpu0
  board_name: haas700

# supported_boards 中记录当前组件能支持的所有板子
supported_boards:
  - haas700: master

hw_info:
