name: rfid_demo
version: master                                     # <必选项> 组件版本号
description: AliOS Things RFID Demo

type: solution

solution:
  cpu_id: cpu0
  board_name: haas100
  # board_name: board_dummy
  # toolchain_prefix: csky-abiv2-elf
  # cpu_name: CK805EF
  # vendor_name: thead
  # chip_name: 'csi_ch2201'
  # ld_script: configs/gcc_eflash.ld
  # ld_script: gcc_eflash.ld

depends:                                       # 该组件依赖其他的组件
  - linksdk: master
  - haas100: master
  - mbedtls: master
  - netmgr: master
  - lwip: master
  - uservice: master
  - wifi: master
  - cli: master
## 第五部分：配置信息
#def_config:                              # 组件的可配置项

# 源文件
source_file:
  - "maintask.c"
  - "main.c"
  - "rfid_demo.c"
  - "rfid_uart.c"
