
## 第一部分： 基础信息
name: ai_agent                                         # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: rel_3.3.0                                     # <必选项> 组件版本号
description: AI推理引擎代理框架，用于接入不同AI推理引擎          # <必选项> 建议至少20字以上
type: common                                        # <必选项> 组件类型，为：solution, chip, board, common, sdk

tag: 通用组件                                       # <可选项> 组件分类，缺省值： ''
keywords:                                           # <可选项> 标签，会影响到组件被搜索的效果，合理的标签很重要
  - base
  - ai agent
license: Apache license v2.0                        # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
depends:
  - ucloud_ai: rel_3.3.0 ? <CONFIG_UCLOUD_AI_ENGINE_ENABLE>

## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  define:
    - CMSIS_NN
  include:
    - include
    - src/engine/
    - src/engine/tflite-micro/
    - src/engine/tflite-micro/third_party/flatbuffers/include/
    - src/engine/tflite-micro/third_party/gemmlowp/
    - src/engine/tflite-micro/third_party/ruy/
    - src/engine/tflite-micro/third_party/cmsis/
    - src/engine/tflite-micro/third_party/cmsis/CMSIS/NN/Include/
    - src/engine/tflite-micro/third_party/cmsis/CMSIS/DSP/Include/
    - src/engine/tflite-micro/third_party/kissfft/

# source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
#   - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件
source_file:
  - src/*.c
  - src/engine/ucloud_ai_engine.c ? <CONFIG_UCLOUD_AI_ENGINE_ENABLE>
  - src/engine/kws_engine.c ? <CONFIG_KWS_AI_ENGINE_ENABLE>
  - src/engine/tflite-micro/tensorflow/lite/micro/*.cc ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
  - src/engine/tflite-micro/tensorflow/lite/micro/cortex_m_generic/*.cc ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
  - src/engine/tflite-micro/tensorflow/lite/micro/kernels/*.cc ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
  - src/engine/tflite-micro/tensorflow/lite/micro/memory_planner/*.cc ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
  - src/engine/tflite-micro/tensorflow/lite/core/api/*.cc ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
  - src/engine/tflite-micro/tensorflow/lite/c/*.c ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
  - src/engine/tflite-micro/tensorflow/lite/kernels/*.cc ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
  - src/engine/tflite-micro/tensorflow/lite/kernels/internal/*.cc ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
  - src/engine/tflite-micro/tensorflow/lite/schema/*.cc ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
  - src/engine/tflite-micro/tensorflow/lite/micro/kernels/cmsis_nn/*.cc ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
#  - src/engine/tflite-micro/third_party/cmsis/CMSIS/NN/Source/ReshapeFunctions/*.c ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
  - src/engine/tflite-micro/third_party/cmsis/CMSIS/NN/Source/NNSupportFunctions/*.c ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
  - src/engine/tflite-micro/third_party/cmsis/CMSIS/NN/Source/PoolingFunctions/*.c ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
  - src/engine/tflite-micro/third_party/cmsis/CMSIS/NN/Source/BasicMathFunctions/*.c ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
#  - src/engine/tflite-micro/third_party/cmsis/CMSIS/NN/Source/ConcatenationFunctions/*.c ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
  - src/engine/tflite-micro/third_party/cmsis/CMSIS/NN/Source/ConvolutionFunctions/*.c ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
  - src/engine/tflite-micro/third_party/cmsis/CMSIS/NN/Source/FullyConnectedFunctions/*.c ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
#  - src/engine/tflite-micro/third_party/cmsis/CMSIS/NN/Source/SVDFunctions/*.c ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
#  - src/engine/tflite-micro/third_party/cmsis/CMSIS/NN/Source/SoftmaxFunctions/*.c ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
  - src/engine/tflite-micro/third_party/cmsis/CMSIS/NN/Source/ActivationFunctions/*.c ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
  - src/engine/tflite-micro/third_party/cmsis/CMSIS/NN/Source/SoftmaxFunctions/arm_softmax_s8.c ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
#  - src/engine/tflite-micro/third_party/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_wrapper_s8.c ? <CONFIG_TFLITE_AI_ENGINE_ENABLE>
  - src/engine/tflite-micro/tensorflow/lite/experimental/microfrontend/lib/fft.cc
  - src/engine/tflite-micro/tensorflow/lite/experimental/microfrontend/lib/fft_util.cc
  - src/engine/tflite-micro/tensorflow/lite/experimental/microfrontend/lib/filterbank.c
  - src/engine/tflite-micro/tensorflow/lite/experimental/microfrontend/lib/filterbank_util.c
  - src/engine/tflite-micro/tensorflow/lite/experimental/microfrontend/lib/frontend.c
  - src/engine/tflite-micro/tensorflow/lite/experimental/microfrontend/lib/frontend_util.c
  - src/engine/tflite-micro/tensorflow/lite/experimental/microfrontend/lib/log_lut.c
  - src/engine/tflite-micro/tensorflow/lite/experimental/microfrontend/lib/log_scale.c
  - src/engine/tflite-micro/tensorflow/lite/experimental/microfrontend/lib/log_scale_util.c
  - src/engine/tflite-micro/tensorflow/lite/experimental/microfrontend/lib/noise_reduction.c
  - src/engine/tflite-micro/tensorflow/lite/experimental/microfrontend/lib/noise_reduction_util.c
  - src/engine/tflite-micro/tensorflow/lite/experimental/microfrontend/lib/pcan_gain_control.c
  - src/engine/tflite-micro/tensorflow/lite/experimental/microfrontend/lib/pcan_gain_control_util.c
  - src/engine/tflite-micro/tensorflow/lite/experimental/microfrontend/lib/window.c
  - src/engine/tflite-micro/tensorflow/lite/experimental/microfrontend/lib/window_util.c
#  - example/aiagent_example.c

## 第五部分：配置信息
def_config:                              # 组件的可配置项

## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相当路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径
install:
  - dest: "include/"
    source:
      - "include/*.h"

## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相当路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"
