
## 第一部分： 基础信息
name: javascript_demo                               # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: rel_3.3.0                                     # <必选项> 组件版本号
description: javascript demo code                   # <必选项> 建议至少20字以上
type: solution                                      # <必选项> 组件类型，为：solution, chip, board, common, sdk

# supported_boards 中记录当前组件能支持的所有板子
supported_boards:
  - haas100: rel_3.3.0
  - haas600: rel_3.3.0
  - haaseduk1: rel_3.3.0
