
## 第一部分： 基础信息
name: javascript_demo                               # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: master                                     # <必选项> 组件版本号
description: javascript demo code                   # <必选项> 建议至少20字以上
type: solution                                      # <必选项> 组件类型，为：solution, chip, board, common, sdk

solution:
  cpu_id: cpu0
  board_name: haas600

hw_info: 




