
## 第一部分： 基础信息
name: documentation                                 # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: dev_aos                                    # <必选项> 组件版本号
description: 文档库包含AliOS Things概述、快速开始、开发工具、构建工具、开发贡献等文档                                   # <必选项> 建议至少20字以上
type: document                                      # <必选项> 组件类型，为：solution, board, chip, arch, drv_core, drv_peripheral, drv_external_device, kernel, common, sdk, document

tag:                                                # <可选项> 组件分类，缺省值： ''
license: Apache license v2.0                        # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD
