name: audio_demo
version: master                                     # <必选项> 组件版本号
description: AliOS Things Audio Demo

type: solution

solution:
  cpu_id: cpu0
  board_name: haas100
  # board_name: board_dummy
  # toolchain_prefix: csky-abiv2-elf
  # cpu_name: CK805EF
  # vendor_name: thead
  # chip_name: 'csi_ch2201'
  # ld_script: configs/gcc_eflash.ld
  # ld_script: gcc_eflash.ld

depends:                                       # 该组件依赖其他的组件
  - linksdk: master
  - haas100: master
  - mbedtls: master
  - netmgr: master
  - a2sa: master
  - uvoice: master
  - littlefs: master
  - lwip: master
  - uservice: master
  - wifi: master
  - cli: master

## 第五部分：配置信息
#def_config:                              # 组件的可配置项
def_config:
  MBEDTLS_CONFIG_TLS_MAX_CONTENT_LEN: 16384 # 增大SSL最大content size，避免播放URL异常
  CONFIG_A7_DSP_ENABLE: 1                  # 使能HaaS100音频驱动开关
  CLI_IOBOX_ENABLE: 1

# 源文件
source_file:
  - "maintask.c"
  - "main.c"
  - "data_model_basic_demo.c"
  - "audio_api.c"
